name: Default Theme
win_feed: 
  title: Feeds
  type: list
  coords: 
    - 0
    - 0
    - 25
    - -1
  colors: 
    h_empty: 32
    box: 4
    a_box: 3
    text: 1
    title: 1
    unread: 6
    a_title: 21
    h_text: 16
    empty: 2
    h_unread: 36
  key: feed
status_bar_cols: 24
win_desc: 
  title: Description
  type: text
  coords: 
    - 25
    - 15
    - -1
    - -1
  colors: 
    f_site: 1
    box: 4
    f_title: 
      - 1
      - bold
    a_box: 3
    text: 1
    title: 1
    date: 6
    f_error: 2
    f_url: 1
    url: 6
    a_title: 21
    h_text: 16
    f_update: 1
    f_desc: 1
  key: desc
window_order: 
  - feed
  - item
  - desc
win_item: 
  title: Items
  type: list
  coords: 
    - 25
    - 0
    - -1
    - 15
  colors: 
    box: 4
    a_box: 3
    text: 1
    title: 1
    unread: 6
    a_title: 21
    h_text: 16
    h_unread: 36
  key: item
url: http://www.pablotron.org/software/raggle/
author: Paul Duncan <pabs@pablotron.org>
